<a href="https://colab.research.google.com/github/soralee2821/coding/blob/master/2021_05_19.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Missing Data

In [1]:
import numpy as np
import pandas as pd

In [2]:
falsy_values = (0, False, None, '', [],{})

In [3]:
any(falsy_values)

False

In [4]:
# NaN : Not a number
np.nan

nan

In [5]:
3 + np.nan

nan

In [6]:
# None is replaced by NaN
a = np.array([1, 2, 3, np.nan, None, 4], dtype=float)

In [7]:
a

array([ 1.,  2.,  3., nan, nan,  4.])

In [8]:
a = np.array([1, 2, 3, np.nan, np.nan, 4])

In [9]:
a.mean()

nan

In [10]:
a.sum()

nan

In [11]:
# infinite value
np.inf

inf

In [12]:
3 + np.inf

inf

In [13]:
np.inf / 3

inf

In [14]:
np.inf / np.inf

nan

In [15]:
b = np.array([1, 2, 3, np.inf, np.nan, 4], dtype=float)

In [16]:
b

array([ 1.,  2.,  3., inf, nan,  4.])

In [17]:
b.sum()

nan

### Checking NaN and Infinite value

In [18]:
np.isnan(np.nan)

True

In [19]:
np.isinf(np.inf)

True

In [20]:
np.isfinite(np.nan), np.isfinite(np.inf)

(False, False)

In [21]:
np.isnan(np.array([1, 2, 3, np.nan, np.inf, 4]))

array([False, False, False,  True, False, False])

In [22]:
np.isinf(np.array([1, 2, 3, np.nan, np.inf, 4]))

array([False, False, False, False,  True, False])

In [23]:
np.isfinite(np.array([1, 2, 3, np.nan, np.inf, 4]))

array([ True,  True,  True, False, False,  True])

### Filtering NaN and Infinite value

In [24]:
a = np.array([1, 2, 3, np.nan, np.nan, 4])

In [25]:
a[~np.isnan(a)]

array([1., 2., 3., 4.])

In [26]:
a[np.isfinite(a)]

array([1., 2., 3., 4.])

In [27]:
a[np.isfinite(a)].sum()

10.0

In [28]:
a[np.isfinite(a)].mean()

2.5