<a href="https://colab.research.google.com/github/soralee2821/coding/blob/master/2021_05_04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

### Basic Numpy Array

In [1]:
import numpy as np

In [2]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [3]:
a = np.array([1,2,3,4])

In [4]:
b = np.array([0,.5,1,1.5,2])

In [5]:
a[0], a[1]

(1, 2)

In [6]:
a[0:]

array([1, 2, 3, 4])

In [7]:
a[1:3]

array([2, 3])

In [8]:
a[::-1]

array([4, 3, 2, 1])

In [9]:
a[::2]

array([1, 3])

In [10]:
b[0], b[2], b[-1]

(0.0, 1.0, 2.0)

In [11]:
a

array([1, 2, 3, 4])

In [12]:
a.dtype

dtype('int64')

In [13]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [14]:
b.dtype

dtype('float64')

In [15]:
np.array([1,2,3,4], dtype=float)

array([1., 2., 3., 4.])

In [16]:
c = np.array(['a','b','c'])

In [17]:
c.dtype

dtype('<U1')

In [18]:
d = np.array({'a':1})

In [19]:
d.dtype

dtype('O')

### Dimentions and shapes

In [20]:
A = np.array([[1,2,3],[4,5,6]])

In [21]:
A.shape

(2, 3)

In [22]:
A.ndim

2

In [23]:
A.size

6

In [24]:
B = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [25]:
B.shape

(2, 2, 3)

In [26]:
B.ndim

3

In [27]:
B.size

12

In [30]:
# the case of inconsistent shape
C = np.array([[[1,2,3],[4,5,6]],[[7,8,9]]])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  


In [31]:
C.shape

(2,)

In [32]:
C.ndim

1

In [33]:
C.size

2