<a href="https://colab.research.google.com/github/soralee2821/coding/blob/master/2021_05_04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

### Basic Numpy Array

In [1]:
import numpy as np

In [2]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [3]:
a = np.array([1,2,3,4])

In [4]:
b = np.array([0,.5,1,1.5,2])

In [5]:
a[0], a[1]

(1, 2)

In [6]:
a[0:]

array([1, 2, 3, 4])

In [7]:
a[1:3]

array([2, 3])

In [8]:
a[::-1]

array([4, 3, 2, 1])

In [9]:
a[::2]

array([1, 3])

In [10]:
b[0], b[2], b[-1]

(0.0, 1.0, 2.0)

In [11]:
a

array([1, 2, 3, 4])

In [12]:
a.dtype

dtype('int64')

In [13]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [14]:
b.dtype

dtype('float64')

In [15]:
np.array([1,2,3,4], dtype=float)

array([1., 2., 3., 4.])

In [16]:
c = np.array(['a','b','c'])

In [17]:
c.dtype

dtype('<U1')

In [18]:
d = np.array({'a':1})

In [19]:
d.dtype

dtype('O')

### Dimentions and shapes