<a href="https://colab.research.google.com/github/soralee2821/coding/blob/master/2021_04_20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Random Numbers

In [1]:
import random

In [2]:
# a random number from 0 to 1
a = random.random()
print(a)

0.5818491351844585


In [3]:
# a random number in the range
a = random.uniform(1,10)
print(a)

7.51129839807193


In [4]:
# a random integer in the range
a = random.randint(1,10)
print(a)

4


In [5]:
# a random integer in the range (the end number X)
a = random.randrange(1,10)
print(a)

5


In [6]:
# a random number in the graph of normal distribution
a = random.normalvariate(0,1)
print(a)

0.4393035857757438


In [7]:
# randomly choose an element in the list
mylist = list("ABCDEFGH")
a = random.choice(mylist)
print(a)

E


In [8]:
# randomly choose unique elements in the list
mylist = list("ABCDEFGH")
a = random.sample(mylist, 3)
print(a)

['E', 'A', 'D']


In [9]:
# randomly choose multiple elements in the list
mylist = list("ABCDEFGH")
a = random.choices(mylist, k=3)
print(a)

['A', 'A', 'E']


In [10]:
# shuffle elements
mylist = list("ABCDEFGH")
random.shuffle(mylist)
print(mylist)

['D', 'E', 'B', 'A', 'G', 'F', 'H', 'C']


In [11]:
# fix the random numbers
random.seed(1)
print(random.random())
print(random.randint(1,10))
random.seed(1)
print(random.random())
print(random.randint(1,10))

0.13436424411240122
2
0.13436424411240122
2


In [12]:
# if the value of seed is the same, the random number is the same
random.seed(1)
print(random.random())
print(random.randint(1,10))
random.seed(2)
print(random.random())
print(random.randint(1,10))
random.seed(1)
print(random.random())
print(random.randint(1,10))

0.13436424411240122
2
0.9560342718892494
1
0.13436424411240122
2


In [13]:
# a random integer from 0 to the number(not include)
import secrets

a = secrets.randbelow(10)
print(a)

6


In [14]:
# a random integer from 0 to the bit number(1111->16)
import secrets

a = secrets.randbits(4)
#1111
print(a)

6


In [15]:
mylist = list("ABCDEFGH")
a = secrets.choice(mylist)
print(a)

B


In [16]:
# n개의 random floats
import numpy as np

a = np.random.rand(3)
print(a)

[0.30916796 0.24752194 0.83608838]


In [17]:
# n by n array-like of random floats

a = np.random.rand(3,3)
print(a)

[[0.82499177 0.21003413 0.4922123 ]
 [0.88785885 0.38917665 0.65083142]
 [0.81969818 0.48335979 0.38758167]]


In [18]:
# random integers in the range with the interval
a = np.random.randint(0,10,3)
print(a)

[2 8 4]


In [19]:
# random integers in the range with n by n array-like
a = np.random.randint(0,10,(3,4))
print(a)

[[9 7 2 3]
 [5 5 4 0]
 [6 6 6 1]]


In [20]:
# switch the first axis in the array(not elements)
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
np.random.shuffle(arr)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[4 5 6]
 [1 2 3]
 [7 8 9]]


In [21]:
np.random.seed(1)
print(np.random.rand(3,3))
np.random.seed(1)
print(np.random.rand(3,3))

[[4.17022005e-01 7.20324493e-01 1.14374817e-04]
 [3.02332573e-01 1.46755891e-01 9.23385948e-02]
 [1.86260211e-01 3.45560727e-01 3.96767474e-01]]
[[4.17022005e-01 7.20324493e-01 1.14374817e-04]
 [3.02332573e-01 1.46755891e-01 9.23385948e-02]
 [1.86260211e-01 3.45560727e-01 3.96767474e-01]]
