<a href="https://colab.research.google.com/github/soralee2821/coding/blob/master/2021_05_05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

### Indexing and Slicing of Matrices

In [1]:
import numpy as np

In [2]:
A = np.array([
              [1,2,3],
              [4,5,6],
              [7,8,9]])

In [3]:
A[1]

array([4, 5, 6])

In [4]:
A[1][0]

4

In [5]:
# A[d1, d2, d3, ...]
A[1, 0]

4

In [6]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [8]:
A[:2, :2]

array([[1, 2],
       [4, 5]])

In [9]:
A[:2, 2:]

array([[3],
       [6]])

In [10]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
A[1] = np.array([10, 10, 10])

In [12]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [13]:
A[2] = 99

In [14]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

### Summary Statistics

In [15]:
a = np.array([1,2,3,4])

In [16]:
a.sum()

10

In [17]:
a.mean()

2.5

In [18]:
a.std()

1.118033988749895

In [19]:
a.var()

1.25

In [20]:
A = np.array([
              [1,2,3],
              [4,5,6],
              [7,8,9]
              ])

In [21]:
A.mean()

5.0

In [22]:
A.std()

2.581988897471611

In [23]:
# sum value of each column
A.sum(axis=0)

array([12, 15, 18])

In [24]:
# sum value of each row
A.sum(axis=1)

array([ 6, 15, 24])

In [26]:
# mean value of each column
A.mean(axis=0)

array([4., 5., 6.])

In [27]:
# mean value of each row
A.mean(axis=1)

array([2., 5., 8.])

In [28]:
# standard deviation value of each column
A.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [29]:
# standard deviation value of each row
A.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

### Broadcasting and Vectorized operations

In [35]:
a = np.arange(4)

In [36]:
a

array([0, 1, 2, 3])

In [37]:
# vectorized operation : operate each element
# when operating, create new array
# does not affect original array
a + 10

array([10, 11, 12, 13])

In [38]:
a * 10

array([ 0, 10, 20, 30])

In [39]:
a

array([0, 1, 2, 3])

In [40]:
# broadcasting operation
a += 10

In [41]:
# affect original array
a

array([10, 11, 12, 13])

In [43]:
a = np.arange(4)

In [44]:
a

array([0, 1, 2, 3])

In [45]:
b = np.array([1,2,3,4])

In [46]:
b

array([1, 2, 3, 4])

In [47]:
a + b

array([1, 3, 5, 7])

In [48]:
a * b

array([ 0,  2,  6, 12])

### Boolean arrays

In [50]:
a = np.arange(4)

In [51]:
a

array([0, 1, 2, 3])

In [53]:
a[0], a[-1]

(0, 3)

In [52]:
a[[0, -1]]

array([0, 3])

In [55]:
# boolean array : True (select the element) / False (on the contrary)
a[[True, False, False, True]]

array([0, 3])

In [56]:
# results in boolean array
a >= 2

array([False, False,  True,  True])

In [57]:
# filter elements with the condition of index
a[a>=2]

array([2, 3])

In [58]:
a.mean()

1.5

In [59]:
a[a > a.mean()]

array([2, 3])

In [62]:
# select elements which does not include condition
a[~(a > a.mean())]

array([0, 1])

In [63]:
# condition 1 or condition 2
a[(a == 0) | (a == 1)]

array([0, 1])

In [65]:
# condition 1 and condition 2
a[(a <= 2) & (a % 2 == 0)]

array([0, 2])

In [66]:
A = np.random.randint(100, size=(3,3))

In [67]:
A

array([[14, 17, 36],
       [38, 55, 62],
       [80, 84, 49]])

In [68]:
A[np.array([
            [True, False, True],
            [False, True, False],
            [True, False, True]
])]

array([14, 36, 55, 80, 49])

In [69]:
A > 30

array([[False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [70]:
A[A > 30]

array([36, 38, 55, 62, 80, 84, 49])