<a href="https://colab.research.google.com/github/soralee2821/coding/blob/master/2021_05_05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

### Indexing and Slicing of Matrices

In [ ]:
import numpy as np

In [ ]:
A = np.array([
              [1,2,3],
              [4,5,6],
              [7,8,9]])

In [ ]:
A[1]

array([4, 5, 6])

In [ ]:
A[1][0]

4

In [ ]:
# A[d1, d2, d3, ...]
A[1, 0]

4

In [ ]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [ ]:
A[:2, :2]

array([[1, 2],
       [4, 5]])

In [ ]:
A[:2, 2:]

array([[3],
       [6]])

In [ ]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
A[1] = np.array([10, 10, 10])

In [ ]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [ ]:
A[2] = 99

In [ ]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

### Summary Statistics

In [ ]:
a = np.array([1,2,3,4])

In [ ]:
a.sum()

10

In [ ]:
a.mean()

2.5

In [ ]:
a.std()

1.118033988749895

In [ ]:
a.var()

1.25

In [ ]:
A = np.array([
              [1,2,3],
              [4,5,6],
              [7,8,9]
              ])

In [ ]:
A.mean()

5.0

In [ ]:
A.std()

2.581988897471611

In [ ]:
# sum value of each column
A.sum(axis=0)

array([12, 15, 18])

In [ ]:
# sum value of each row
A.sum(axis=1)

array([ 6, 15, 24])

In [ ]:
# mean value of each column
A.mean(axis=0)

array([4., 5., 6.])

In [ ]:
# mean value of each row
A.mean(axis=1)

array([2., 5., 8.])

In [ ]:
# standard deviation value of each column
A.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [ ]:
# standard deviation value of each row
A.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

### Broadcasting and Vectorized operations

In [ ]:
a = np.arange(4)

In [ ]:
a

array([0, 1, 2, 3])

In [ ]:
# vectorized operation : operate each element
# when operating, create new array
# does not affect original array
a + 10

array([10, 11, 12, 13])

In [ ]:
a * 10

array([ 0, 10, 20, 30])

In [ ]:
a

array([0, 1, 2, 3])

In [ ]:
# broadcasting operation
a += 10

In [ ]:
# affect original array
a

array([10, 11, 12, 13])

In [ ]:
a = np.arange(4)

In [ ]:
a

array([0, 1, 2, 3])

In [ ]:
b = np.array([1,2,3,4])

In [ ]:
b

array([1, 2, 3, 4])

In [ ]:
a + b

array([1, 3, 5, 7])

In [ ]:
a * b

array([ 0,  2,  6, 12])

### Boolean arrays

In [ ]:
a = np.arange(4)

In [ ]:
a

array([0, 1, 2, 3])

In [ ]:
a[0], a[-1]

(0, 3)

In [ ]:
a[[0, -1]]

array([0, 3])

In [ ]:
# boolean array : True (select the element) / False (on the contrary)
a[[True, False, False, True]]

array([0, 3])

In [ ]:
# results in boolean array
a >= 2

array([False, False,  True,  True])

In [ ]:
# filter elements with the condition of index
a[a>=2]

array([2, 3])

In [ ]:
a.mean()

1.5

In [ ]:
a[a > a.mean()]

array([2, 3])

In [ ]:
# select elements which does not include condition
a[~(a > a.mean())]

array([0, 1])

In [ ]:
# condition 1 or condition 2
a[(a == 0) | (a == 1)]

array([0, 1])

In [ ]:
# condition 1 and condition 2
a[(a <= 2) & (a % 2 == 0)]

array([0, 2])

In [ ]:
A = np.random.randint(100, size=(3,3))

In [ ]:
A

array([[14, 17, 36],
       [38, 55, 62],
       [80, 84, 49]])

In [ ]:
A[np.array([
            [True, False, True],
            [False, True, False],
            [True, False, True]
])]

array([14, 36, 55, 80, 49])

In [ ]:
A > 30

array([[False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
A[A > 30]

array([36, 38, 55, 62, 80, 84, 49])

### Linear Algebra

In [ ]:
A = np.array([
              [1,2,3],
              [4,5,6],
              [7,8,9]
])

In [ ]:
B = np.array([
              [6,5],
              [4,3],
              [1,2]
])

In [ ]:
A.dot(B)

array([[17, 17],
       [50, 47],
       [83, 77]])

In [ ]:
A @ B

array([[17, 17],
       [50, 47],
       [83, 77]])

In [ ]:
B.T

array([[6, 4, 1],
       [5, 3, 2]])

In [ ]:
B.T @ A

array([[29, 40, 51],
       [31, 41, 51]])

### Size of objects in Memory

In [ ]:
import sys

In [ ]:
# An integer in Python > 24bytes
sys.getsizeof(1)

28

In [ ]:
# Long integers are even larger
sys.getsizeof(10**100)

72

In [82]:
# Numpy size is much smaller
np.dtype(int).itemsize

8

In [83]:
np.dtype(float).itemsize

8

In [84]:
l = list(range(1000))

In [85]:
a = np.arange(1000)

In [86]:
%time np.sum(a ** 2)

CPU times: user 166 µs, sys: 0 ns, total: 166 µs
Wall time: 172 µs


332833500

In [87]:
# performance with numpy is faster than that of list
%time sum([x ** 2 for x in l])

CPU times: user 0 ns, sys: 314 µs, total: 314 µs
Wall time: 325 µs


332833500